/**
 * generated by Xtext 2.13.0
 */
package org.example.expressions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.example.expressions.ui.AbstractExpressionsUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ExpressionsUiModule extends AbstractExpressionsUiModule {
  public ExpressionsUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
