/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.smalljava.ui.contentassist;

import org.xtext.example.smalljava.ui.contentassist.AbstractSmallJavaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SmallJavaProposalProvider extends AbstractSmallJavaProposalProvider {
}
