/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.smalljava.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SmallJavaProposalProvider extends AbstractSmallJavaProposalProvider {
}
