/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.smalljava.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.smalljava.ui.AbstractSmallJavaUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SmallJavaUiModule extends AbstractSmallJavaUiModule {
  public SmallJavaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
