/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.smalljava.smallJava.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.smalljava.smallJava.SJParameter;
import org.xtext.example.smalljava.smallJava.SmallJavaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SJ Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SJParameterImpl extends SJSymbolImpl implements SJParameter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SJParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmallJavaPackage.Literals.SJ_PARAMETER;
  }

} //SJParameterImpl
