/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.smalljava.smallJava.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.smalljava.smallJava.SJStatement;
import org.xtext.example.smalljava.smallJava.SmallJavaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SJ Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SJStatementImpl extends MinimalEObjectImpl.Container implements SJStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SJStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmallJavaPackage.Literals.SJ_STATEMENT;
  }

} //SJStatementImpl
