/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.smalljava.smallJava.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.smalljava.smallJava.SJThis;
import org.xtext.example.smalljava.smallJava.SmallJavaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SJ This</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SJThisImpl extends SJExpressionImpl implements SJThis
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SJThisImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmallJavaPackage.Literals.SJ_THIS;
  }

} //SJThisImpl
