/**
 * generated by Xtext 2.13.0
 */
package org.example.expressions.scoping;

import org.example.expressions.scoping.AbstractExpressionsScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ExpressionsScopeProvider extends AbstractExpressionsScopeProvider {
}
