/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.smalljava.smallJava;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SJ Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smalljava.smallJava.SJClass#getSuperclass <em>Superclass</em>}</li>
 *   <li>{@link org.xtext.example.smalljava.smallJava.SJClass#getMembers <em>Members</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.smalljava.smallJava.SmallJavaPackage#getSJClass()
 * @model
 * @generated
 */
public interface SJClass extends SJNamedElement
{
  /**
   * Returns the value of the '<em><b>Superclass</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Superclass</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Superclass</em>' reference.
   * @see #setSuperclass(SJClass)
   * @see org.xtext.example.smalljava.smallJava.SmallJavaPackage#getSJClass_Superclass()
   * @model
   * @generated
   */
  SJClass getSuperclass();

  /**
   * Sets the value of the '{@link org.xtext.example.smalljava.smallJava.SJClass#getSuperclass <em>Superclass</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Superclass</em>' reference.
   * @see #getSuperclass()
   * @generated
   */
  void setSuperclass(SJClass value);

  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.smalljava.smallJava.SJMember}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Members</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see org.xtext.example.smalljava.smallJava.SmallJavaPackage#getSJClass_Members()
   * @model containment="true"
   * @generated
   */
  EList<SJMember> getMembers();

} // SJClass
