/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.smalljava.smallJava;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SJ Null</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.smalljava.smallJava.SmallJavaPackage#getSJNull()
 * @model
 * @generated
 */
public interface SJNull extends SJExpression
{
} // SJNull
