/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.smalljava.smallJava;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SJ Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.smalljava.smallJava.SJProgram#getClasses <em>Classes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.smalljava.smallJava.SmallJavaPackage#getSJProgram()
 * @model
 * @generated
 */
public interface SJProgram extends EObject
{
  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.smalljava.smallJava.SJClass}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Classes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see org.xtext.example.smalljava.smallJava.SmallJavaPackage#getSJProgram_Classes()
   * @model containment="true"
   * @generated
   */
  EList<SJClass> getClasses();

} // SJProgram
