/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.smalljava.smallJava;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.smalljava.smallJava.SmallJavaFactory
 * @model kind="package"
 * @generated
 */
public interface SmallJavaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "smallJava";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/smalljava/SmallJava";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "smallJava";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SmallJavaPackage eINSTANCE = org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJProgramImpl <em>SJ Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJProgramImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJProgram()
   * @generated
   */
  int SJ_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_PROGRAM__CLASSES = 0;

  /**
   * The number of structural features of the '<em>SJ Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJNamedElementImpl <em>SJ Named Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJNamedElementImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJNamedElement()
   * @generated
   */
  int SJ_NAMED_ELEMENT = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_NAMED_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>SJ Named Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_NAMED_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJClassImpl <em>SJ Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJClassImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJClass()
   * @generated
   */
  int SJ_CLASS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_CLASS__NAME = SJ_NAMED_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Superclass</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_CLASS__SUPERCLASS = SJ_NAMED_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_CLASS__MEMBERS = SJ_NAMED_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>SJ Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_CLASS_FEATURE_COUNT = SJ_NAMED_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJMemberImpl <em>SJ Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJMemberImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJMember()
   * @generated
   */
  int SJ_MEMBER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_MEMBER__NAME = SJ_NAMED_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_MEMBER__TYPE = SJ_NAMED_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>SJ Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_MEMBER_FEATURE_COUNT = SJ_NAMED_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJFieldImpl <em>SJ Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJFieldImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJField()
   * @generated
   */
  int SJ_FIELD = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_FIELD__NAME = SJ_MEMBER__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_FIELD__TYPE = SJ_MEMBER__TYPE;

  /**
   * The number of structural features of the '<em>SJ Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_FIELD_FEATURE_COUNT = SJ_MEMBER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJMethodImpl <em>SJ Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJMethodImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJMethod()
   * @generated
   */
  int SJ_METHOD = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_METHOD__NAME = SJ_MEMBER__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_METHOD__TYPE = SJ_MEMBER__TYPE;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_METHOD__PARAMS = SJ_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_METHOD__BODY = SJ_MEMBER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>SJ Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_METHOD_FEATURE_COUNT = SJ_MEMBER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJSymbolImpl <em>SJ Symbol</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJSymbolImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJSymbol()
   * @generated
   */
  int SJ_SYMBOL = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_SYMBOL__NAME = SJ_NAMED_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_SYMBOL__TYPE = SJ_NAMED_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>SJ Symbol</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_SYMBOL_FEATURE_COUNT = SJ_NAMED_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJParameterImpl <em>SJ Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJParameterImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJParameter()
   * @generated
   */
  int SJ_PARAMETER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_PARAMETER__NAME = SJ_SYMBOL__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_PARAMETER__TYPE = SJ_SYMBOL__TYPE;

  /**
   * The number of structural features of the '<em>SJ Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_PARAMETER_FEATURE_COUNT = SJ_SYMBOL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJBlockImpl <em>SJ Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJBlockImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJBlock()
   * @generated
   */
  int SJ_BLOCK = 6;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_BLOCK__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>SJ Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJStatementImpl <em>SJ Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJStatementImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJStatement()
   * @generated
   */
  int SJ_STATEMENT = 7;

  /**
   * The number of structural features of the '<em>SJ Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJReturnImpl <em>SJ Return</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJReturnImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJReturn()
   * @generated
   */
  int SJ_RETURN = 8;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_RETURN__EXPRESSION = SJ_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>SJ Return</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_RETURN_FEATURE_COUNT = SJ_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJVariableDeclarationImpl <em>SJ Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJVariableDeclarationImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJVariableDeclaration()
   * @generated
   */
  int SJ_VARIABLE_DECLARATION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_VARIABLE_DECLARATION__NAME = SJ_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_VARIABLE_DECLARATION__TYPE = SJ_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_VARIABLE_DECLARATION__EXPRESSION = SJ_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>SJ Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_VARIABLE_DECLARATION_FEATURE_COUNT = SJ_STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJIfStatementImpl <em>SJ If Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJIfStatementImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJIfStatement()
   * @generated
   */
  int SJ_IF_STATEMENT = 10;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_IF_STATEMENT__EXPRESSION = SJ_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_IF_STATEMENT__THEN_BLOCK = SJ_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_IF_STATEMENT__ELSE_BLOCK = SJ_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>SJ If Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_IF_STATEMENT_FEATURE_COUNT = SJ_STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJExpressionImpl <em>SJ Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJExpressionImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJExpression()
   * @generated
   */
  int SJ_EXPRESSION = 13;

  /**
   * The number of structural features of the '<em>SJ Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_EXPRESSION_FEATURE_COUNT = SJ_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJAssignmentImpl <em>SJ Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJAssignmentImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJAssignment()
   * @generated
   */
  int SJ_ASSIGNMENT = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_ASSIGNMENT__LEFT = SJ_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_ASSIGNMENT__RIGHT = SJ_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>SJ Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_ASSIGNMENT_FEATURE_COUNT = SJ_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJMemberSelectionImpl <em>SJ Member Selection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJMemberSelectionImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJMemberSelection()
   * @generated
   */
  int SJ_MEMBER_SELECTION = 15;

  /**
   * The feature id for the '<em><b>Receiver</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_MEMBER_SELECTION__RECEIVER = SJ_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Member</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_MEMBER_SELECTION__MEMBER = SJ_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Methodinvocation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_MEMBER_SELECTION__METHODINVOCATION = SJ_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_MEMBER_SELECTION__ARGS = SJ_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>SJ Member Selection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_MEMBER_SELECTION_FEATURE_COUNT = SJ_EXPRESSION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJThisImpl <em>SJ This</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJThisImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJThis()
   * @generated
   */
  int SJ_THIS = 16;

  /**
   * The number of structural features of the '<em>SJ This</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_THIS_FEATURE_COUNT = SJ_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJNullImpl <em>SJ Null</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJNullImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJNull()
   * @generated
   */
  int SJ_NULL = 17;

  /**
   * The number of structural features of the '<em>SJ Null</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_NULL_FEATURE_COUNT = SJ_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.BoolConstantImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getBoolConstant()
   * @generated
   */
  int BOOL_CONSTANT = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT__VALUE = SJ_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bool Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT_FEATURE_COUNT = SJ_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJSymbolRefImpl <em>SJ Symbol Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJSymbolRefImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJSymbolRef()
   * @generated
   */
  int SJ_SYMBOL_REF = 19;

  /**
   * The feature id for the '<em><b>Symbol</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_SYMBOL_REF__SYMBOL = SJ_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>SJ Symbol Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_SYMBOL_REF_FEATURE_COUNT = SJ_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.smalljava.smallJava.impl.SJNewImpl <em>SJ New</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.smalljava.smallJava.impl.SJNewImpl
   * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJNew()
   * @generated
   */
  int SJ_NEW = 20;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_NEW__TYPE = SJ_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>SJ New</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SJ_NEW_FEATURE_COUNT = SJ_EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJProgram <em>SJ Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Program</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJProgram
   * @generated
   */
  EClass getSJProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smalljava.smallJava.SJProgram#getClasses <em>Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Classes</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJProgram#getClasses()
   * @see #getSJProgram()
   * @generated
   */
  EReference getSJProgram_Classes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJClass <em>SJ Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Class</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJClass
   * @generated
   */
  EClass getSJClass();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.smalljava.smallJava.SJClass#getSuperclass <em>Superclass</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Superclass</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJClass#getSuperclass()
   * @see #getSJClass()
   * @generated
   */
  EReference getSJClass_Superclass();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smalljava.smallJava.SJClass#getMembers <em>Members</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Members</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJClass#getMembers()
   * @see #getSJClass()
   * @generated
   */
  EReference getSJClass_Members();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJMember <em>SJ Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Member</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJMember
   * @generated
   */
  EClass getSJMember();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.smalljava.smallJava.SJMember#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJMember#getType()
   * @see #getSJMember()
   * @generated
   */
  EReference getSJMember_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJField <em>SJ Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Field</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJField
   * @generated
   */
  EClass getSJField();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJMethod <em>SJ Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Method</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJMethod
   * @generated
   */
  EClass getSJMethod();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smalljava.smallJava.SJMethod#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJMethod#getParams()
   * @see #getSJMethod()
   * @generated
   */
  EReference getSJMethod_Params();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smalljava.smallJava.SJMethod#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJMethod#getBody()
   * @see #getSJMethod()
   * @generated
   */
  EReference getSJMethod_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJParameter <em>SJ Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Parameter</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJParameter
   * @generated
   */
  EClass getSJParameter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJBlock <em>SJ Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Block</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJBlock
   * @generated
   */
  EClass getSJBlock();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smalljava.smallJava.SJBlock#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJBlock#getStatements()
   * @see #getSJBlock()
   * @generated
   */
  EReference getSJBlock_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJStatement <em>SJ Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Statement</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJStatement
   * @generated
   */
  EClass getSJStatement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJReturn <em>SJ Return</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Return</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJReturn
   * @generated
   */
  EClass getSJReturn();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smalljava.smallJava.SJReturn#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJReturn#getExpression()
   * @see #getSJReturn()
   * @generated
   */
  EReference getSJReturn_Expression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJVariableDeclaration <em>SJ Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Variable Declaration</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJVariableDeclaration
   * @generated
   */
  EClass getSJVariableDeclaration();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smalljava.smallJava.SJVariableDeclaration#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJVariableDeclaration#getExpression()
   * @see #getSJVariableDeclaration()
   * @generated
   */
  EReference getSJVariableDeclaration_Expression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJIfStatement <em>SJ If Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ If Statement</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJIfStatement
   * @generated
   */
  EClass getSJIfStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smalljava.smallJava.SJIfStatement#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJIfStatement#getExpression()
   * @see #getSJIfStatement()
   * @generated
   */
  EReference getSJIfStatement_Expression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smalljava.smallJava.SJIfStatement#getThenBlock <em>Then Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then Block</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJIfStatement#getThenBlock()
   * @see #getSJIfStatement()
   * @generated
   */
  EReference getSJIfStatement_ThenBlock();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smalljava.smallJava.SJIfStatement#getElseBlock <em>Else Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Block</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJIfStatement#getElseBlock()
   * @see #getSJIfStatement()
   * @generated
   */
  EReference getSJIfStatement_ElseBlock();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJSymbol <em>SJ Symbol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Symbol</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJSymbol
   * @generated
   */
  EClass getSJSymbol();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.smalljava.smallJava.SJSymbol#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJSymbol#getType()
   * @see #getSJSymbol()
   * @generated
   */
  EReference getSJSymbol_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJNamedElement <em>SJ Named Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Named Element</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJNamedElement
   * @generated
   */
  EClass getSJNamedElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smalljava.smallJava.SJNamedElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJNamedElement#getName()
   * @see #getSJNamedElement()
   * @generated
   */
  EAttribute getSJNamedElement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJExpression <em>SJ Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Expression</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJExpression
   * @generated
   */
  EClass getSJExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJAssignment <em>SJ Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Assignment</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJAssignment
   * @generated
   */
  EClass getSJAssignment();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smalljava.smallJava.SJAssignment#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJAssignment#getLeft()
   * @see #getSJAssignment()
   * @generated
   */
  EReference getSJAssignment_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smalljava.smallJava.SJAssignment#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJAssignment#getRight()
   * @see #getSJAssignment()
   * @generated
   */
  EReference getSJAssignment_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJMemberSelection <em>SJ Member Selection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Member Selection</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJMemberSelection
   * @generated
   */
  EClass getSJMemberSelection();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.smalljava.smallJava.SJMemberSelection#getReceiver <em>Receiver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Receiver</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJMemberSelection#getReceiver()
   * @see #getSJMemberSelection()
   * @generated
   */
  EReference getSJMemberSelection_Receiver();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.smalljava.smallJava.SJMemberSelection#getMember <em>Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Member</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJMemberSelection#getMember()
   * @see #getSJMemberSelection()
   * @generated
   */
  EReference getSJMemberSelection_Member();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smalljava.smallJava.SJMemberSelection#isMethodinvocation <em>Methodinvocation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Methodinvocation</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJMemberSelection#isMethodinvocation()
   * @see #getSJMemberSelection()
   * @generated
   */
  EAttribute getSJMemberSelection_Methodinvocation();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.smalljava.smallJava.SJMemberSelection#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJMemberSelection#getArgs()
   * @see #getSJMemberSelection()
   * @generated
   */
  EReference getSJMemberSelection_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJThis <em>SJ This</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ This</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJThis
   * @generated
   */
  EClass getSJThis();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJNull <em>SJ Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Null</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJNull
   * @generated
   */
  EClass getSJNull();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.BoolConstant <em>Bool Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Constant</em>'.
   * @see org.xtext.example.smalljava.smallJava.BoolConstant
   * @generated
   */
  EClass getBoolConstant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.smalljava.smallJava.BoolConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.smalljava.smallJava.BoolConstant#getValue()
   * @see #getBoolConstant()
   * @generated
   */
  EAttribute getBoolConstant_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJSymbolRef <em>SJ Symbol Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ Symbol Ref</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJSymbolRef
   * @generated
   */
  EClass getSJSymbolRef();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.smalljava.smallJava.SJSymbolRef#getSymbol <em>Symbol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Symbol</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJSymbolRef#getSymbol()
   * @see #getSJSymbolRef()
   * @generated
   */
  EReference getSJSymbolRef_Symbol();

  /**
   * Returns the meta object for class '{@link org.xtext.example.smalljava.smallJava.SJNew <em>SJ New</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SJ New</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJNew
   * @generated
   */
  EClass getSJNew();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.smalljava.smallJava.SJNew#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.example.smalljava.smallJava.SJNew#getType()
   * @see #getSJNew()
   * @generated
   */
  EReference getSJNew_Type();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SmallJavaFactory getSmallJavaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJProgramImpl <em>SJ Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJProgramImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJProgram()
     * @generated
     */
    EClass SJ_PROGRAM = eINSTANCE.getSJProgram();

    /**
     * The meta object literal for the '<em><b>Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_PROGRAM__CLASSES = eINSTANCE.getSJProgram_Classes();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJClassImpl <em>SJ Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJClassImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJClass()
     * @generated
     */
    EClass SJ_CLASS = eINSTANCE.getSJClass();

    /**
     * The meta object literal for the '<em><b>Superclass</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_CLASS__SUPERCLASS = eINSTANCE.getSJClass_Superclass();

    /**
     * The meta object literal for the '<em><b>Members</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_CLASS__MEMBERS = eINSTANCE.getSJClass_Members();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJMemberImpl <em>SJ Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJMemberImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJMember()
     * @generated
     */
    EClass SJ_MEMBER = eINSTANCE.getSJMember();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_MEMBER__TYPE = eINSTANCE.getSJMember_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJFieldImpl <em>SJ Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJFieldImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJField()
     * @generated
     */
    EClass SJ_FIELD = eINSTANCE.getSJField();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJMethodImpl <em>SJ Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJMethodImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJMethod()
     * @generated
     */
    EClass SJ_METHOD = eINSTANCE.getSJMethod();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_METHOD__PARAMS = eINSTANCE.getSJMethod_Params();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_METHOD__BODY = eINSTANCE.getSJMethod_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJParameterImpl <em>SJ Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJParameterImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJParameter()
     * @generated
     */
    EClass SJ_PARAMETER = eINSTANCE.getSJParameter();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJBlockImpl <em>SJ Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJBlockImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJBlock()
     * @generated
     */
    EClass SJ_BLOCK = eINSTANCE.getSJBlock();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_BLOCK__STATEMENTS = eINSTANCE.getSJBlock_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJStatementImpl <em>SJ Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJStatementImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJStatement()
     * @generated
     */
    EClass SJ_STATEMENT = eINSTANCE.getSJStatement();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJReturnImpl <em>SJ Return</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJReturnImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJReturn()
     * @generated
     */
    EClass SJ_RETURN = eINSTANCE.getSJReturn();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_RETURN__EXPRESSION = eINSTANCE.getSJReturn_Expression();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJVariableDeclarationImpl <em>SJ Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJVariableDeclarationImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJVariableDeclaration()
     * @generated
     */
    EClass SJ_VARIABLE_DECLARATION = eINSTANCE.getSJVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_VARIABLE_DECLARATION__EXPRESSION = eINSTANCE.getSJVariableDeclaration_Expression();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJIfStatementImpl <em>SJ If Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJIfStatementImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJIfStatement()
     * @generated
     */
    EClass SJ_IF_STATEMENT = eINSTANCE.getSJIfStatement();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_IF_STATEMENT__EXPRESSION = eINSTANCE.getSJIfStatement_Expression();

    /**
     * The meta object literal for the '<em><b>Then Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_IF_STATEMENT__THEN_BLOCK = eINSTANCE.getSJIfStatement_ThenBlock();

    /**
     * The meta object literal for the '<em><b>Else Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_IF_STATEMENT__ELSE_BLOCK = eINSTANCE.getSJIfStatement_ElseBlock();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJSymbolImpl <em>SJ Symbol</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJSymbolImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJSymbol()
     * @generated
     */
    EClass SJ_SYMBOL = eINSTANCE.getSJSymbol();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_SYMBOL__TYPE = eINSTANCE.getSJSymbol_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJNamedElementImpl <em>SJ Named Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJNamedElementImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJNamedElement()
     * @generated
     */
    EClass SJ_NAMED_ELEMENT = eINSTANCE.getSJNamedElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SJ_NAMED_ELEMENT__NAME = eINSTANCE.getSJNamedElement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJExpressionImpl <em>SJ Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJExpressionImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJExpression()
     * @generated
     */
    EClass SJ_EXPRESSION = eINSTANCE.getSJExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJAssignmentImpl <em>SJ Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJAssignmentImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJAssignment()
     * @generated
     */
    EClass SJ_ASSIGNMENT = eINSTANCE.getSJAssignment();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_ASSIGNMENT__LEFT = eINSTANCE.getSJAssignment_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_ASSIGNMENT__RIGHT = eINSTANCE.getSJAssignment_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJMemberSelectionImpl <em>SJ Member Selection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJMemberSelectionImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJMemberSelection()
     * @generated
     */
    EClass SJ_MEMBER_SELECTION = eINSTANCE.getSJMemberSelection();

    /**
     * The meta object literal for the '<em><b>Receiver</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_MEMBER_SELECTION__RECEIVER = eINSTANCE.getSJMemberSelection_Receiver();

    /**
     * The meta object literal for the '<em><b>Member</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_MEMBER_SELECTION__MEMBER = eINSTANCE.getSJMemberSelection_Member();

    /**
     * The meta object literal for the '<em><b>Methodinvocation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SJ_MEMBER_SELECTION__METHODINVOCATION = eINSTANCE.getSJMemberSelection_Methodinvocation();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_MEMBER_SELECTION__ARGS = eINSTANCE.getSJMemberSelection_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJThisImpl <em>SJ This</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJThisImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJThis()
     * @generated
     */
    EClass SJ_THIS = eINSTANCE.getSJThis();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJNullImpl <em>SJ Null</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJNullImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJNull()
     * @generated
     */
    EClass SJ_NULL = eINSTANCE.getSJNull();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.BoolConstantImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getBoolConstant()
     * @generated
     */
    EClass BOOL_CONSTANT = eINSTANCE.getBoolConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_CONSTANT__VALUE = eINSTANCE.getBoolConstant_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJSymbolRefImpl <em>SJ Symbol Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJSymbolRefImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJSymbolRef()
     * @generated
     */
    EClass SJ_SYMBOL_REF = eINSTANCE.getSJSymbolRef();

    /**
     * The meta object literal for the '<em><b>Symbol</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_SYMBOL_REF__SYMBOL = eINSTANCE.getSJSymbolRef_Symbol();

    /**
     * The meta object literal for the '{@link org.xtext.example.smalljava.smallJava.impl.SJNewImpl <em>SJ New</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.smalljava.smallJava.impl.SJNewImpl
     * @see org.xtext.example.smalljava.smallJava.impl.SmallJavaPackageImpl#getSJNew()
     * @generated
     */
    EClass SJ_NEW = eINSTANCE.getSJNew();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SJ_NEW__TYPE = eINSTANCE.getSJNew_Type();

  }

} //SmallJavaPackage
