/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.smalljava.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.smalljava.SmallJavaRuntimeModule;
import org.xtext.example.smalljava.SmallJavaStandaloneSetup;
import org.xtext.example.smalljava.ide.SmallJavaIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SmallJavaIdeSetup extends SmallJavaStandaloneSetup {
  @Override
  public Injector createInjector() {
    SmallJavaRuntimeModule _smallJavaRuntimeModule = new SmallJavaRuntimeModule();
    SmallJavaIdeModule _smallJavaIdeModule = new SmallJavaIdeModule();
    return Guice.createInjector(Modules2.mixin(_smallJavaRuntimeModule, _smallJavaIdeModule));
  }
}
