/**
 * generated by Xtext 2.13.0
 */
package org.example.expressions;

import org.example.expressions.AbstractExpressionsRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ExpressionsRuntimeModule extends AbstractExpressionsRuntimeModule {
}
