/**
 * generated by Xtext 2.13.0
 */
package org.example.expressions.ide;

import org.example.expressions.ide.AbstractExpressionsIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ExpressionsIdeModule extends AbstractExpressionsIdeModule {
}
