/**
 * generated by Xtext 2.13.0
 */
package org.example.expressions.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.expressions.ExpressionsRuntimeModule;
import org.example.expressions.ExpressionsStandaloneSetup;
import org.example.expressions.ide.ExpressionsIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ExpressionsIdeSetup extends ExpressionsStandaloneSetup {
  @Override
  public Injector createInjector() {
    ExpressionsRuntimeModule _expressionsRuntimeModule = new ExpressionsRuntimeModule();
    ExpressionsIdeModule _expressionsIdeModule = new ExpressionsIdeModule();
    return Guice.createInjector(Modules2.mixin(_expressionsRuntimeModule, _expressionsIdeModule));
  }
}
