/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.smalljava.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.smalljava.parser.antlr.internal.InternalSmallJavaParser;
import org.xtext.example.smalljava.services.SmallJavaGrammarAccess;

public class SmallJavaParser extends AbstractAntlrParser {

	@Inject
	private SmallJavaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSmallJavaParser createParser(XtextTokenStream stream) {
		return new InternalSmallJavaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SJProgram";
	}

	public SmallJavaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmallJavaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
