/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.smalljava


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SmallJavaStandaloneSetup extends SmallJavaStandaloneSetupGenerated {

	def static void doSetup() {
		new SmallJavaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
