/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.smalljava.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSmallJavaScopeProvider extends DelegatingScopeProvider {
}
