/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.smalljava;

import org.xtext.example.smalljava.AbstractSmallJavaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmallJavaRuntimeModule extends AbstractSmallJavaRuntimeModule {
}
